### ISSUE TITLE
404: /manual/en/mail.configuration.php

### ISSUE THREAD

**Issue by rhacius** [hhvm/user-documentation#174] opened 2015-12-06 01:12 UTC
Please complete the information below:

# How I got to this page:

- - - eg "I clicked a link on <address of other site>" - - -

# What I expected to find here:

- - - eg "Documentation tell me how to <do something>" - - -

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2015-12-04T23:13:16+0000:09a12875e831327fbf5be42a9c0198c688af2433:bfa816e32c7b1a74e7aaee3d2688af2112439003
 - Page requested: /manual/en/mail.configuration.php
 - Page requested at: Sun, 06 Dec 2015 01:12:32 +0000

**Comment by JoelMarcey** [comment] 2015-12-06 01:17
A couple of things...

1. With the new docs, we are not going to be duplicating php.net information. This page is a php.net page.

2. We need make the redirects to php.net happen correctly and that is a current open issue. #165 

This should hopefully be worked on early next week.

**Comment by fredemmott** [comment] 2015-12-06 03:26
I'm going to close this as a dupe of #165 in a few days, I'm leaving this open for now, as it would be really helpful if you could share how you got to this page - was it from google, a link on a blog (if so, which?)?

While we're confident that redirecting to php.net is the best thing to do (as Joel said, the page was just an exact copy of the PHP documentation), it would be good to try and fix whatever led you to looking for it on the HHVM site in the first place.

**Comment by fredemmott** [comment] 2015-12-07 19:11
@rhacius ^^^

**Closed** 2015-12-08 18:05 UTC
Labels: duplicate
