### ISSUE TITLE
Add long-form php.net articles to search

### ISSUE THREAD

**Issue by JoelMarcey** [hhvm/user-documentation#344] opened 2016-07-08 15:45 UTC
HHVM supports many PHP constructs that we don't duplicate in our documentation. Maybe link to results from there in our search. 

New search may have removed the function/class linking to php.net. But we might also be able to link to long-form articles.

**Comment by fredemmott** [comment] 2016-07-08 16:44
Non-article part is dupe of https://github.com/hhvm/user-documentation/issues/337

**Comment by fredemmott** [comment] 2017-12-18 20:18
Won't be doing this, as part of https://hhvm.com/blog/2017/09/18/the-future-of-hhvm.html

**Closed by fredemmott** 2017-12-18 20:18 UTC
