### ISSUE TITLE
Example Code Won't Work

### ISSUE THREAD

**Issue by patriciamckenzie** [hhvm/user-documentation#390] opened 2016-11-15 17:49 UTC
Please complete the information below:

# Where is the problem?

I'm using the sample from 
https://docs.hhvm.com/hhvm/basic-usage/command-line

w/ fibonacci.

# What is the problem?

The code will not run:
mckenzie$ hhvm NovemberFifteen.php 10

Catchable fatal error: Hack type error: Expected modifier at /Users/mckenzie/Documents/MckenziePlayground/NovEleventh.php line 5
--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2016-10-05T21:47:03+0000:7e6e72a26df5c3d1ecc8feb244d6ef6d8d5dc924:3bcf6ed75043817b82363c6f7aa00050ccc8ff53
 - Page requested: /hhvm/basic-usage/command-line
 - Page requested at: Tue, 15 Nov 2016 17:47:10 +0000
 - Controller: GuidePageController

**Comment by fredemmott** [comment] 2016-11-15 17:54
Please put NovemberFifteen.php on to gist.github.com and link it here, and also give your HHVM version.

Can't reproduce this either by copy-pasting, or directly downloading the example:

```
[fredemmott@devbig349.prn1 /tmp] cd hhtest
[fredemmott@devbig349.prn1 /tmp/hhtest] touch .hhconfig
[fredemmott@devbig349.prn1 /tmp/hhtest] wget https://raw.githubusercontent.com/hhvm/user-documentation/master/guides/hhvm/02-basic-usage/02-command-line-examples/fib.php
--2016-11-15 09:53:28--  https://raw.githubusercontent.com/hhvm/user-documentation/master/guides/hhvm/02-basic-usage/02-command-line-examples/fib.php
Resolving fwdproxy... 2401:db00:11:df0e:face:b00c:0:aa, 10.47.128.15
Connecting to fwdproxy|2401:db00:11:df0e:face:b00c:0:aa|:8080... connected.
Proxy request sent, awaiting response... 200 OK
Length: 335 [text/plain]
Saving to: “fib.php”

100%[===========================================>] 335         --.-K/s   in 0s

2016-11-15 09:53:28 (111 MB/s) - “fib.php” saved [335/335]

[fredemmott@devbig349.prn1 /tmp/hhtest] hhvm fib.php 10
The 10 number in fibonacci is: 55
```

**Comment by fredemmott** [comment] 2017-12-18 20:17
Closing: can't reproduce, and the deploy process automatically runs all examples and checks expected output.

**Closed** 2017-12-18 20:16 UTC
