### ISSUE TITLE
odd wording of conversion rules

### ISSUE THREAD

**Issue by zenogantner** [hhvm/user-documentation#1353] opened 2023-10-22 01:00 UTC
Please complete the information below:

# Where is the problem?

https://docs.hhvm.com/hack/types/type-conversion

# What is the problem?

"No non-bool type can be converted implicitly to bool. All other conversions must be explicit." should be "No non-bool type can be converted implicitly to bool. All conversions must be explicit."

Same for int and float.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.164.0:HSL=v4.108.1:2023-10-21T01:56:32+0000:1fa47f258c6b68f8ec01899aa82fd6ffa0957109
 - Page requested: /hack/types/type-conversion
 - Page requested at: Sun, 22 Oct 2023 00:55:46 +0000
 - Controller: GuidePageController

**Comment by lexidor** [comment] 2023-10-22 11:11
Hi, thank you for reporting this. I believe this issue to be a duplicate of #1334. Could you please explain how my belief is mistaken?

**Comment by zenogantner** [comment] 2023-10-22 14:46
You're right.

**Closed** 2023-10-22 14:55 UTC
