### ISSUE TITLE
The Release Schedule page is outdated

### ISSUE THREAD

**Issue by derickr** [hhvm/user-documentation#313] opened 2016-04-26 09:25 UTC
Please complete the information below:

# Where is the problem?

https://docs.hhvm.com/hhvm/installation/release-schedule

# What is the problem?

It only goes up to 3.12, and misses 3.13 and future releases.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2016-03-25T19:44:16+0000:59945858b91b58253f39c91d5ff11f685e228917:ded7f690201f02c37531b00bb6a6fc0091e9945e
 - Page requested: /hhvm/installation/release-schedule
 - Page requested at: Tue, 26 Apr 2016 09:24:07 +0000
 - Controller: GuidePageController

**Comment by ricordisamoa** [comment] 2016-04-27 06:49
dupe of #306?

**Closed** 2016-04-28 18:17 UTC
Labels: duplicate
