### ISSUE TITLE
Can't scroll up on Opera on Android

### ISSUE THREAD

**Issue by atmartins** [hhvm/user-documentation#406] opened 2017-01-14 20:58 UTC
Please complete the information below:

# Where is the problem?

On the website, e.g. https://docs.hhvm.com/hhvm/installation/introduction

# What is the problem?

I can't scroll up on an Android phone. Nexus 5, Opera browser. I can scroll down the page but trying to scroll up triggers a pull to refresh function.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2017-01-03T20:16:48+0000:84ad9cd989e2467bb262c8d3cbe326bbdde54163:14202af5a6cd7ba7c897ddf934a4967aca952405
 - Page requested: /hhvm/installation/introduction
 - Page requested at: Sat, 14 Jan 2017 20:54:37 +0000
 - Controller: GuidePageController

**Comment by mofarrell** [comment] 2017-01-17 15:52
I don't really know what we are doing that might cause pull down to refresh to be buggy.  If this is reproducible in more mobile browsers, this might be interesting to look at.

**Comment by Orvid** [comment] 2017-01-17 18:35
Which version of Opera? Opera mini (both 21 & 22) definitely does have rendering issues, but I can't replicate the issue you're experiencing. The full version of Opera (41) does not appear to have the same issue.

**Comment by AndrewDiMola** [comment] 2021-03-04 00:45
Closing because I couldn't replicate this issue on Android with Opera or Opera Mini.

**Closed by AndrewDiMola** 2021-03-04 00:45 UTC
