### ISSUE TITLE
Typo/error in documentation about Ref

### ISSUE THREAD

**Issue by jwatzman** [hhvm/user-documentation#732] opened 2019-10-01 18:13 UTC
Please complete the information below:

# Where is the problem?

Typo/error in the third paragraph.

# What is the problem?

> In eralAsync, it's preferable to refactor to use return values or [...]

What is `eralAsync`?

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.24.0:HSL=v4.15.2:2019-09-27T19:26:48+0000:366bffbc3df5e5484e531b534e5b0d2c64dd862a
 - Page requested: /hsl/reference/class/HH.Lib.Ref/
 - Page requested at: Tue, 01 Oct 2019 18:11:33 +0000
 - Controller: APIClassPageController

**Comment by jwatzman** [comment] 2019-10-01 18:14
I think this is dupe #731

**Comment by jjergus** [comment] 2019-10-01 19:17
Yes, duplicate of #731

**Closed by jjergus** 2019-10-01 19:17 UTC
