### ISSUE TITLE
"3704 errors found" when executing a clean install following the Getting Started guide.

### ISSUE THREAD

**Issue by edcasillas** [hhvm/user-documentation#921] opened 2020-10-01 03:46 UTC
# Where is the problem?

https://docs.hhvm.com/hack/getting-started/starting-a-real-project

Steps shown in the "Getting Started: Starting A Real Project" guide before the "Adding Functions or Classes".

# What is the problem?

Following each one of the steps of this guide (installing Composer, creating an empty .hhconfig file, src and tests directories, configuring autoloading and use Composer to install dependencies), either manually or executing the script shown in the "An Example" section, provokes that running "hh_client" show "3704 errors found"; expected behavior would be to receive "No Errors!".

See this attachment for details on the output: [Terminal Saved Output.txt](https://github.com/hhvm/user-documentation/files/5309356/Terminal.Saved.Output.txt)

This makes the rest of the tutorial rather impossible to follow along.

**EDIT**
Found this post at SO: https://stackoverflow.com/questions/62978039/hh-client-reports-errors-on-package

By adding `allowed_fixme_codes_strict = 2050, 4110` to the `.hhconfig` file, the count of errors goes down to 65 (it's better, but still not fixed).

Output: [Terminal Saved Output 2.txt](https://github.com/hhvm/user-documentation/files/5309378/Terminal.Saved.Output.2.txt)

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.74.0:HSL=v4.41.0:2020-09-24T18:02:02+0000:1fa47f258c6b68f8ec01899aa82fd6ffa0957109
 - Page requested: /hack/getting-started/starting-a-real-project
 - Page requested at: Thu, 01 Oct 2020 01:35:17 +0000
 - Controller: GuidePageController

**Comment by lexidor** [comment] 2020-10-01 20:51
Hi, this is indeed a known problem. I have not had much time recently to update the docs about this. This issue is a duplicate of #905 and #904. You can follow the steps I gave in #904. I will also put up a PR #923 to update the docs, so the docs should hopefully be fixed shortly.

**Closed by lexidor** 2020-10-01 20:51 UTC
