### ISSUE TITLE
Updating TODO comment from Object-instance-checks

### ISSUE THREAD

**Issue by leeys202** [hhvm/user-documentation#532] opened 2018-06-19 22:12 UTC
Please complete the information below:

# Where is the problem?

Section about object instance checks:
https://docs.hhvm.com/hack/types/refining#object-instance-checks

# What is the problem?

In the above link, under the definition of Child class, there is a TODO comment about adding a link to `<<__override>>` attribute when it is ready. I think the link can definitely be added now (https://docs.hhvm.com/hack/attributes/special#__override)

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2018-05-22T20:33:05+0000:bb89df40dd6e5a8501362ce41535876ebcfa4d3f
 - Page requested: /hack/types/refining
 - Page requested at: Tue, 19 Jun 2018 22:09:49 +0000
 - Controller: GuidePageController

**Comment by Wilfred** [comment] 2018-10-19 16:47
Duplicate of #502.

**Closed by Wilfred** 2018-10-19 16:47 UTC
